---
:base_path: "/root/.gemstash"
:cache_type: memory
:db_adapter: postgres
:db_url: <%= ENV["DATABASE_URL"] %>
:db_connection_options: # Sequel.connect options
  :connect_timeout: 10
  :read_timeout: 5
  :timeout: 30
:protected_fetch: false
:fetch_timeout: 20
